name: Reploy React app to S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@4
      - name: install
        run: npm install
      - name: Buildbuild
        run: npm run build
